### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by ioquatix** [socketry/falcon#12]
@janko-m:

> If you're curious, this is what MemoryProfiler currently says about reading from the rack.input:
> 
> ```
> allocated memory by location
> -----------------------------------
>   26737873  /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.12.3/lib/async/io/stream.rb:209
>   26593287  /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/falcon-0.17.5/lib/falcon/adapters/input.rb:81
>    4249600  /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.12.3/lib/async/io/generic.rb:128
>    1484800  /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.12.3/lib/async/io/generic.rb:47
>     512000  /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.12.3/lib/async/io/stream.rb:186
>     489447  /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/falcon-0.17.5/lib/falcon/adapters/input.rb:80
> ```
>
> (That's for a 50MB request body)

Here is the current implementation from Ruby of `str_byte_substr`:

```c
static VALUE
str_byte_substr(VALUE str, long beg, long len, int empty)
{
    char *p, *s = RSTRING_PTR(str);
    long n = RSTRING_LEN(str);
    VALUE str2;

    if (beg > n || len < 0) return Qnil;
    if (beg < 0) {
	beg += n;
	if (beg < 0) return Qnil;
    }
    if (len > n - beg)
	len = n - beg;
    if (len <= 0) {
	if (!empty) return Qnil;
	len = 0;
	p = 0;
    }
    else
	p = s + beg;

    if (!STR_EMBEDDABLE_P(len, TERM_LEN(str)) && SHARABLE_SUBSTRING_P(beg, len, n)) {
	str2 = rb_str_new_frozen(str);
	str2 = str_new_shared(rb_obj_class(str2), str2);
	RSTRING(str2)->as.heap.ptr += beg;
	RSTRING(str2)->as.heap.len = len;
    }
    else {
	str2 = rb_str_new_with_class(str, p, len);
    }

    str_enc_copy(str2, str);

    if (RSTRING_LEN(str2) == 0) {
	if (!rb_enc_asciicompat(STR_ENC_GET(str)))
	    ENC_CODERANGE_SET(str2, ENC_CODERANGE_VALID);
	else
	    ENC_CODERANGE_SET(str2, ENC_CODERANGE_7BIT);
    }
    else {
	switch (ENC_CODERANGE(str)) {
	  case ENC_CODERANGE_7BIT:
	    ENC_CODERANGE_SET(str2, ENC_CODERANGE_7BIT);
	    break;
	  default:
	    ENC_CODERANGE_SET(str2, ENC_CODERANGE_UNKNOWN);
	    break;
	}
    }

    OBJ_INFECT_RAW(str2, str);

    return str2;
}
```

I'm trying to figure out what part of this is causing problems.

**Comment by ioquatix** [comment]
The two entry points in `string.c` are `rb_str_byteslice` and `rb_str_slice_bang`. Ideally we want to add `rb_str_byteslice_bang`.

**Comment by ioquatix** [comment]
Here is branch: https://github.com/ioquatix/ruby/tree/fix-byteslice

**Comment by ioquatix** [comment]
I am a little bit suspicious of

```c
    if (!STR_EMBEDDABLE_P(len, TERM_LEN(str)) && SHARABLE_SUBSTRING_P(beg, len, n)) {
	str2 = rb_str_new_frozen(str);
	str2 = str_new_shared(rb_obj_class(str2), str2);
	RSTRING(str2)->as.heap.ptr += beg;
	RSTRING(str2)->as.heap.len = len;
    }
```

**Comment by ioquatix** [comment]
When I comment out that section of code, the tests pass.

**Comment by ioquatix** [comment]
So, it appears that the following is happening:

1. Make a new frozen string from the input string. If the input string is frozen, this is a no-op. Otherwise, it makes a copy.
2. It makes a sharable (copy on write?) instance of the frozen string.
3. It adjusts the `ptr` and `len` of this copy as required by `substr`.

The frozen string generated in step 1 is leaked.

It seems like one solution would be to only apply this optimisation if the source string is already frozen.

**Comment by ioquatix** [comment]
Another thing to consider is that the allocations actually share the same underlying memory allocation. So, it shows up as two strings, but they both point to the same memory (just different parts). However, I fail to see how this is an optimisation if the source string is not frozen. It just a appears to make a copy of the entire string which only part is used.

**Comment by ioquatix** [comment]
So, I thought a bit more, and it seems like we can avoid this memory copy of we freeze the buffer before calling `#byteslice`. So I tried doing that here: https://github.com/socketry/falcon/commit/4d4340ac8f198a4cd8eb88205a517eee706b959a

@janko-m do you mind seeing if this improves/reduces memory allocations?

**Comment by janko-m** [comment]
I tested the change on `falcon` now, and it doesn't appear to improve memory usage.

**Comment by ioquatix** [comment]
@janko-m do you think you can make a spec in falcon so I can see how to test this?

**Comment by ioquatix** [comment]
@janko-m Bump :)

**Comment by ioquatix** [comment]
@janko-m if you have some time to follow up with this, I believe we've made some big improvements. That being said, if you don't have time, I'm happy where we currently stand, so feel free to close this issue.

**Comment by janko-m** [comment]
@ioquatix Hey, sorry for the delay on this. I believe I should have time this week to test out the integration again, and share the current status.

I'm also happy with the memory improvements we've made so far, I will try to come up with the high-level Falcon spec for the memory usage just to have it.

**Comment by ioquatix** [comment]
That sounds awesome! Looking forward to the PR.

**Comment by janko-m** [comment]
After all the improvements we've done so far, with removing the Rack input rewindability when it's not needed, and with memory allocation specs, I think the memory usage is good enough 👍 

I ideally wanted to eliminate extra string allocations that were coming from reading the request body, but that led to a deep rabbit hole of figuring out how Ruby manages strings, and I feel like I've hit one too many walls. I might still come back to that in the future to take another stab at it, because I want to figure it out.

The important thing is that everything is done in a streaming fashion, so Ruby's GC can make sure memory usage doesn't grow uncontrollably.

**Comment by janko-m** [comment]
After all the improvements we've done so far, with removing the Rack input rewindability when it's not needed, and with memory allocation specs, I think the memory usage is good enough 👍 

I ideally wanted to eliminate extra string allocations that were coming from reading the request body, but that led to a deep rabbit hole of figuring out how Ruby manages strings, and I feel like I've hit one too many walls. I might still come back to that in the future to take another stab at it, because I want to figure it out.

The important thing is that everything is done in a streaming fashion, so Ruby's GC can make sure memory usage doesn't grow uncontrollably.

**Comment by janko-m** [comment]
After all the improvements we've done so far, with removing the Rack input rewindability when it's not needed, and with memory allocation specs, I think the memory usage is good enough 👍 

I ideally wanted to eliminate extra string allocations that were coming from reading the request body, but that led to a deep rabbit hole of figuring out how Ruby manages strings, and I feel like I've hit one too many walls. I might still come back to that in the future to take another stab at it, because I want to figure it out.

The important thing is that everything is done in a streaming fashion, so Ruby's GC can make sure memory usage doesn't grow uncontrollably.
