### ISSUE TITLE
`falcon serve` on blank rails app with ruby 3.0.0 fails 

### ISSUE THREAD

**Issue by scally** [socketry/falcon#138]
```
/Users/sean/.rvm/gems/ruby-3.0.0/gems/railties-6.1.1/lib/rails/initializable.rb:60 in `run_initializers'
/Users/sean/.rvm/gems/ruby-3.0.0rve.rb:60 in `load_app'
 /Users/sean/.rvm/gems/ruby-3.0.0/gems/falcon-0.37.2/lib/falcon/controller/serve.rb:89 in `block (2 levels) in setup'
/Users/sean/.rvm/gems/ruby-3.0.0/gems/async-1.28.3/lib/async/task.rb:265 in `block in make_fiber'
Caused by TypeError: nil can't be coerced into Float
→ /Users/sean/.rvm/gems/ruby-3.0.0/gems/timers-4.3.2/lib/timers/timer.rb:103 in `+'
```

A blank app will boot with ruby 3.0 and rails 6.1 using `rails s`. Removing puma and adding falcon to the gem file and then running `falcon serve` results in this error.

**Comment by the-spectator** [comment]
I can reproduce the issue on my system. I tracked the error in the `listen` gem, method `wait_for_state` is passing timeout as nil, due to incorrect passing of arguments.

Relevant  Code: https://github.com/guard/listen/blob/f0572f7bbca48fb832d4ada5a61d729db0d20a88/lib/listen/event/loop.rb#L55-L59

System configuration
```
ruby version: 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
rails: 6.1.1
falcon: 0.37.2
async: 1.28.3
listen: 3.4.0
```

**Comment by the-spectator** [comment]
I have created https://github.com/guard/listen/pull/529 to resolve this issue on listen master.

**Comment by scally** [comment]
confirmed, bumping to latest listen solves this problem
