### ISSUE TITLE
Support for Sinatra streaming responses

### ISSUE THREAD

**Issue by veesahni** [socketry/falcon#158]
What is needed for falcon to support [sinatra streaming responses](https://github.com/sinatra/sinatra/blob/cf404526373298f06a59e1a129b6cdf8282ae216/README.md#streaming-responses)?

The following works with thin (1.8.1), but not with falcon (0.39.2):

config.ru
```ruby
require './app'
run Sinatra::Application
```

app.rb
```ruby
require 'sinatra'

get '/stream', :provides => 'text/event-stream' do
    stream :keep_open do |out|
      $conn = out
      $conn << "init\n"
    end
end


get '/send' do
  if $conn
    $conn << "msg\n"
  end

  "ok\n"
end
```

**Comment by ioquatix** [comment]
It looks like Sinatra hard codes their implementation since Rack doesn't provide any generic way to achieve this generally.

https://github.com/sinatra/sinatra/blame/master/lib/sinatra/base.rb#L478

More details are discussed here:

https://github.com/rack/rack/pull/1745

In order to support streaming with Sinatra, you'd need to make a PR to Sinatra. The best option currently available is rack partial hijack which is fully supported by Falcon.

**Comment by veesahni** [comment]
I went back to basic principles, since I realized that sinatra streaming responses may not be necessary in a world where blocking calls yield.

**Option 1**

This kindof worked.  The concurrency part is working fine, but the problem seems to be rack or sinatra is buffering responses internally.  Couldn't find a way around this, even when using a simpler object that responded to .each

```ruby
get '/stream' do
  reader, $writer = IO.pipe

  $writer.puts "init\n"
  reader  # responds to .each
end

get '/send' do
  $writer.puts "msg\n"
  
  "ok\n"
end
```

**Option 2**

Then I took your hint about using hijack, and got myself an io that doesn't buffer.  This works well:

```ruby
get '/stream' do
  $q = Queue.new

  io = env['rack.hijack'].call
  io.write "HTTP/1.1 200 OK\n"
  io.write "Content-Type: text/stream;charset=utf-8\n"
  io.write "Connection: Close\n\n"

  io.write "init\n"
  loop do
    io.write $q.pop
  end
end

get '/send' do
  $q.push "msg\n"
  
  "ok\n"
end
```

**Comment by ioquatix** [comment]
Option 1 looks okay to me. Option 2 will break HTTP/2 (or just won't work at all since hijack is not supported).

**Comment by veesahni** [comment]
For completeness (and anyone else discovering this issue):

**Option 3**

An implementation using partial hijack.  I've verified both concurrency works and there's no buffering issue.  Only oddity here is server insists on sending 'transfer-encoding: chunked' header, even though we're not really chunking.

```ruby
get '/stream' do
  $q = Queue.new

  response.headers['rack.hijack'] = proc do |io|
    io.write "init\n"

    loop do
      io.write $q.pop
    end
  end

  200
end

get '/send' do
  $q.push "msg\n"
  
  "ok\n"
end
```

**Comment by ioquatix** [comment]
Option 3 is the correct one.

Regarding chunked encoding, it's the only way you can send a response without a content length known ahead of time and keep the connection open. Otherwise, you'd need to close the connection.

In https://github.com/rack/rack/pull/1745 I discuss supporting this more explicitly, e.g.

``` ruby
get '/stream' do
  $q = Queue.new

  proc do |io|
    io.write "init\n"

    loop do
      io.write $q.pop
    end
  end
end

get '/send' do
  $q.push "msg\n"
  
  "ok\n"
end
```

**Comment by ioquatix** [comment]
If you like this idea, please voice your support on the Rack issue.
