### ISSUE TITLE
Logs not printing to STDOUT

### ISSUE THREAD

**Issue by sudhirj** [socketry/falcon#28]
Apps with the rails_12factor gem / apps running on Heroku need to print logs to STDOUT - but falcon seems to be blocking this. On Heroku it dumps the logs only on exit. Can we have logging behaviour respected / flushed when the app is trying to log to STDOUT?

**Comment by ioquatix** [comment]
Thanks for the report.

I'm not completely sure I understand the problem.

I'm running a demo app in Heroku and the logs come out just fine:

<img width="1079" alt="screen shot 2018-10-25 at 9 10 00 am" src="https://user-images.githubusercontent.com/30030/47458360-d7c9e800-d835-11e8-8daf-e4dff9d48912.png">

So, I don't believe logging goes to `STDOUT` but goes to `STDERR`:

https://github.com/socketry/async/blob/master/lib/async/logger.rb#L42

Do you mind showing me how you are starting falcon (do you include `--verbose`) and do you mind showing me the log output window on Heroku after running some requests?

**Comment by sudhirj** [comment]
<img width="1475" alt="screenshot 2018-10-25 at 9 32 01 pm" src="https://user-images.githubusercontent.com/21678/47514277-9bca6d80-d89d-11e8-9612-a4dcd0a87229.png">

Here's what I mean - only the Heroku router logs are shown when the requests are made, but when I restart and SIGTERM is sent, all the logs are dumped. 

This is the Rails 5.2.1 with the `RAILS_LOG_TO_STDOUT=enabled`, with the default production.rb settings. 
```
if ENV["RAILS_LOG_TO_STDOUT"].present?
    logger           = ActiveSupport::Logger.new(STDOUT)
    logger.formatter = config.log_formatter
    config.logger    = ActiveSupport::TaggedLogging.new(logger)
end
```

**Comment by sudhirj** [comment]
Not using verbose mode, start command is `web: bundle exec falcon serve --port $PORT --bind http://0.0.0.0`

**Comment by ioquatix** [comment]
I just deployed the latest version of falcon and https://github.com/socketry/utopia-falcon-heroku to Heroku and the logging is certainly happening in real time as I make individual requests.

I took a look at rails_12factor and see that it pulls in the following code:

https://github.com/heroku/rails_stdout_logging/blob/master/lib/rails_stdout_logging/rails.rb#L2-L4

It seems to me that it's likely to stop `::Logger` from working correctly. I'd say the issue here is not with Falcon (which uses `::Logger`) and with `rails_stdout_logging` which is breaking `::Logger`.
