### ISSUE TITLE
Threaded mode segfaults on SIGINT

### ISSUE THREAD

**Issue by julik** [socketry/falcon#47]
To reproduce, I run `falcon` with the following `config.ru`:

https://gist.github.com/julik/477b0b13edbef798b34ba22cc99391e6

When the request gets processed a number of times, and I issue Ctrl+C in the terminal where Falcon is running, MRI crashes in enumerator.

https://gist.github.com/julik/c4dd842f035b0aa824fcc6ae7b01a56f

**Comment by julik** [comment]
And the full crash log https://gist.github.com/julik/1cb1bab2b048d6d5b24fbe3bfd512f06

**Comment by ioquatix** [comment]
Thanks I will check what is going on.

**Comment by ioquatix** [comment]
This is a known bug with 2.5 - use 2.6 or the latest version of 2.5 which I thinks the back port applied now.

https://bugs.ruby-lang.org/issues/14561

Can you try if the issue is reproducible with the latest 2.5 or 2.6 release?

**Comment by ioquatix** [comment]
I have tested this and cannot reproduce on the latest 2.6, but I did have this problem on 2.5 - the fix was back-ported recently, so hopefully it works on the latest 2.5 - the work-around is to not use `--threaded` mode on MRI.

Feel free to let me know if you are still having issues. Thanks for reporting the problem.
