### ISSUE TITLE
Falcon::Adapters::Input#gets doesn't comply with the Rack specification

### ISSUE THREAD

**Issue by janko-m** [socketry/falcon#5]
The Rack specification says that the `#gets` method should behave like `IO#gets`, but currently it just retrieves the whole request body. I don't know who uses that method in the first place (I always use `#read`), but I thought it would be good to make Falcon fully Rack-compliant.

**Comment by ioquatix** [comment]
That makes sense.

**Comment by ioquatix** [comment]
We'd need to copy something like https://github.com/socketry/async-io/blob/c39a819204c18864f66f354f1e1034dab31e2874/lib/async/io/stream.rb#L74-L85

**Comment by ioquatix** [comment]
The specification for `gets` is completely insane:

```
gets(sep=$/ [, getline_args]) → string or nil click to toggle source
gets(limit [, getline_args]) → string or nil
gets(sep, limit [, getline_args]) → string or nil
```

> Reads the next “line'' from the I/O stream; lines are separated by sep. A separator of nil reads the entire contents, and a zero-length separator reads the input a paragraph at a time (two successive newlines in the input separate paragraphs). The stream must be opened for reading or an IOError will be raised. The line read in will be returned and also assigned to $_. Returns nil if called at end of file. If the first argument is an integer, or optional second argument is given, the returning string would not be longer than the given value in bytes.

**Comment by ioquatix** [comment]
I started implementing this. It's a huge abomination.

Then, I wondered, what does the rack spec actually say?

https://www.rubydoc.info/github/rack/rack/master/file/SPEC#The_Input_Stream

> The input stream is an IO-like object which contains the raw HTTP POST data. When applicable, its external encoding must be “ASCII-8BIT” and it must be opened in binary mode, for Ruby 1.9 compatibility. The input stream must respond to gets, each, read and rewind.

And specifically:

> **gets must be called without arguments and return a string, or nil on EOF.**

It seems like a conforming implementation just needs to call `#read`, which is exactly what we are doing already.

Please discuss this if you think this interpretation is incorrect, because as I said, it would be good to get this right. But, implementing `IO#gets` is really nasty.
