### ISSUE TITLE
Falcon hanging on OS X Catalina (10.15)

### ISSUE THREAD

**Issue by saluzafa** [socketry/falcon#79]
Hello all !

I just discovered Falcon and was testing it locally on my Mac but Falcon is hanging and stops processing requests after few seconds.

**Context**
 I created a `config.ru` file with this content (from `examples/hello/config.ru` directory):
```ruby
run lambda { |env| Async.logger.info(self) {env['HTTP_USER_AGENT']}; [200, {}, ["Hello World"]] }
```

Then I'm starting Falcon with these options:
```falcon serve -b http://localhost:9292 --count 1```

Everything runs well at that point but when I'm testing request throughput with `siege` or `ab` Falcon just hangs and stops processing requests.
Used Siege command: `siege -c 1 http://127.0.0.1:9292`
Used AB command: `ab -c 1 -n 10000 http://127.0.0.1:9292/`

The strange thing is that if I wait like 30 seconds - 1 minutes, Falcon will start to process requests again (without restarting it).
I checked `netstat -n | grep TIME_WAIT | wc -l`, before running any benchmark tool it was giving my `1` and after running a benchmark tool for few seconds it was `20041`.
It seems that connections are not "closed" (not sure if it's that :/), is there a solution for that ?

Thanks for the great work you are doing on this project + `async-*` projects, they are AWESOME :).

Cheers

**Comment by saluzafa** [comment]
Just tested with `wrk` tool and it seems to work well with it: `wrk -t12 -c200 -d30s http://127.0.0.1:9292/`
So, maybe it's just a bug in `siege` and `ab` tools :/

**Comment by ioquatix** [comment]
So, it's probably a bug which is odd because I use macos for development and never had this issue.

That being said, the macOS network stack, not to put too finer point on it, pretty wonky.

I've seen quite a bit of strage behaviour when making lots of sockets - unexplained slowdowns when using sockets, etc. `wrk` makes 8 connections and then reuses those connections for the duration of the benchmark, while `ab` makes one connection per request (HTTP/1.0 non persistent connections).

So, honestly, my gut reaction is, this is just another manifestation of macOS being buggy when dealing with lots of sockets.

If you have a moment, try running the async-io c10k spec several times in a row, then wait like 5 minutes and run it again. Every subsequent run should get less connections /second, but if you leave it a while it seems like eventually get gets back to normal.

Maybe the sockets do need to time out in the kernel and they have some kind of O(N) algorithm per socket?

**Comment by tleish** [comment]
The default ephemeral port range on macOS/OSX is 49152-65535, which is only 16,383 ports:

    $ sysctl -a | grep portrange
    net.inet.ip.portrange.lowfirst: 1023
    net.inet.ip.portrange.lowlast: 600
    net.inet.ip.portrange.first: 49152
    net.inet.ip.portrange.last: 65535
    net.inet.ip.portrange.hifirst: 49152
    net.inet.ip.portrange.hilast: 65535

To increase the range, reduce the value of `first` and `hifirst`:

    sudo sysctl -w net.inet.ip.portrange.first=32768
    sudo sysctl -w net.inet.ip.portrange.hifirst=32768

References
* https://serverfault.com/questions/145907/does-mac-os-x-throttle-the-rate-of-socket-creation
* https://stackoverflow.com/questions/7938869/ab-is-erroring-out-with-apr-socket-recv-connection-refused-61
* https://stackoverflow.com/a/30357879/537554
* https://serverfault.com/a/145937/91715

**Comment by ioquatix** [comment]
@tleish thanks for your summary, I believe that addresses the original issue. I do a lot of development on MacOS and have not seen this issue in practice, however as far as benchmarking goes, I've definitely run into issues e.g. lack of file descriptors, etc.

**Comment by ioquatix** [comment]
@saluzafa if you want to test with `ab` the more recent versions have a `-k` option to use persistent connections. Maybe you can try that and let me know if that solves your problem.
